### ISSUE TITLE
Fehler beim Neustarten des Netzwerkes

### ISSUE THREAD

**Issue by herda** [PSE-blockchain-evoting/EVote#134]
1. Klick auf "Wahl endgültig beenden" im Admin-Klient
2. Folgender Fehler tritt auf (Siehe Screenshot)

![screenshot from 2018-09-03 17-54-55](https://user-images.githubusercontent.com/7550731/44995408-321b9a80-afa3-11e8-89f9-ff0deb89db83.png)

**Comment by Schaback** [comment]
Das Problem ist vermutlich das Leerzeichen im Dateipfad.

**Comment by Schaback** [comment]
Sämtliche Hyperledger Startup-Skripte unterstützen keine Leerzeichen im Pfad.
