### ISSUE TITLE
Wahl endet nicht bei extra Endbedingung

### ISSUE THREAD

**Issue by herda** [PSE-blockchain-evoting/EVote#135]
1. Absolute Mehrheitswahl mit 4 Kandidaten und 3 Wähler
2. Extra Endbedingung 100% Wähler-Prozentsatz
3. Alle 3 Wähler haben gewählt
4. Wahl wird trotzdem nicht beendet.

![screenshot from 2018-09-03 18-10-18](https://user-images.githubusercontent.com/7550731/44995752-d2be8a00-afa4-11e8-9052-ac9724a39d76.png)

**Comment by tinytiny123** [comment]
Beide extra Endbedingungen prüfen im Moment auf ein echt Größer, nicht auf ein größer gleich.
Wird umgestellt.

**Comment by tinytiny123** [comment]
Fixed with 91aa9b6ce3b1501dbd30c08e73ba4ad2f3cbe7f8
