### ISSUE TITLE
Extra-Endbedingung "Kandidat Prozentsatz" geht auch nicht

### ISSUE THREAD

**Issue by herda** [PSE-blockchain-evoting/EVote#136]
1. Absolute Mehrheitswahl - 2 Kandidaten, 4 Wähler
2. Extra-Endbedingung 75% Kandidat Prozentsatz
3. Erste 3 Wähler wählen "ja", der letzte Wähler wählt "nein"
4. Wahl wird erst am Ende der Zeit beendet.

![screenshot from 2018-09-03 18-27-24](https://user-images.githubusercontent.com/7550731/44996442-444c0780-afa8-11e8-9c96-41ac9856819d.png)

**Comment by tinytiny123** [comment]
Beide extra Endbedingungen prüfen im Moment auf ein echt Größer, nicht auf ein größer gleich.
Wird umgestellt.

**Comment by tinytiny123** [comment]
Fixed with 91aa9b6ce3b1501dbd30c08e73ba4ad2f3cbe7f8
