### ISSUE TITLE
Wenn nach Beendigung einer Wahl (manuell durch den Wahllleiter) eine Wähler-GUI noch geöffnet bleibt, wird in dieser nicht über das Wahlende informiert.

### ISSUE THREAD

**Issue by mi-ki** [PSE-blockchain-evoting/EVote#146]
Siehe Titel.

**Comment by Schaback** [comment]
Dieser Fehler lässt sich ohne Events aus dem Hyperledger-Framework nicht lösen, da alle Klienten beim Beenden der Wahl die Verbindung zum Netzwerk verlieren.
