### ISSUE TITLE
Implement ElectionDataIF <-> JSON-String conversion

### ISSUE THREAD

**Issue by Schaback** [PSE-blockchain-evoting/EVote#23]
1. in InitializationInvocation
2. in ElectionDataTypeQuery

**Comment by tinytiny123** [comment]
Transmit enums as their names not as integer value.

**Comment by tinytiny123** [comment]
Also end condition should include a property "type" which contains name of the end condition.

**Comment by tinytiny123** [comment]
Sample JSON:
`{
	"name" : "CooleWahl",
	"description" : "Diese Wahl is  sehr cool",
	"votingSystem" : "ABSOLUTEMAJORITY",
	"candidates" : [
		"hans",
		"peter",
		"werner"
	],
	"candidateDescriptions" : [
		"cooler dude",
		"nicer mensch",
		"sicker kerl"
	],
	"startDate" : "Mon Jan _2 15:04:05 MST 2006",
	"endDate" : "Wed Jan _4 15:04:05 MST 2006",
	"endCondition" : {
		"type" : "VoterPercentileCondition",
		"percentage" : "60"
	}
}`

**Comment by Schaback** [comment]
New Sample (missing parameter and changed date format):
```json
{
  "name": "CooleWahl",
  "description": "Diese Wahl is sehr cool",
  "votingSystem": "ABSOLUTEMAJORITY",
  "candidates": [
    "hans",
    "peter",
    "werner"
  ],
  "candidateDescriptions": [
    "cooler dude",
    "nicer mensch",
    "sicker kerl"
  ],
  "startDate": 1136210645,
  "endDate": 1136383445,
  "endCondition": {
    "type": "VoterPercentileCondition",
    "percentage": "60"
  },
  "voterCount": 3
}
```

**Comment by Schaback** [comment]
Implemented conversion in direction JSON -> ElectionDataIF (see 897635016d991386fd9a85bad346fd7abc2df9c5)
